### ISSUE TITLE
Kanun Maddelerinin Tebliğ Maddesi ile ilişkilendirilmesi

### ISSUE THREAD

**Issue by hudiys01** [hudiys01/HUD-IYS#15]

**Comment by arifyildirim** [comment]
İlişkilendirme
HUD İYS kapsamında bulunan dokümanlardan ilgili olanlar, birbirleri ile ilişkilendirilebilecek. İlişkilendirme işlemi dokümanların tamamı esas alınarak yapılabileceği gibi dokümanlarda yer alan belli bir metin, paragraf veya metin bloğu itibari ile de yapılabilecektir.
Örnekler: 
• Gelir Vergisi Kanunu (GVK)  94 üncü maddesinin 6 numaralı bendi ile 120 Sıra No’lu Gelir Vergisi Kanunu Genel Tebliğinin II. Bölümü
• Gelir Vergisi Kanunu (GVK) 1 inci maddesi ile Kurumlar Vergisi Kanununu (KVK) 1 inci maddesi
• Katma Değer Vergisi Kanunu (KDVK) 9 uncu maddesi ile 105 Sıra No’lu Gelir Vergisi Genel Tebliği’nin 3 üncü bölümü 
• Kurumlar Vergisi Kanunu (KVK) 1 inci 2 nci ve 3 üncü maddeleri ile ilgili olarak Oluş Yayımcılık tarafından hazırlanan ***\* no’lu sirküler
• Katma Değer Vergisi Kanunu’nun (KDVK) 11 inci maddesi ile ilgili olarak  Hesap Uzmanı X tarafından hazırlanan sunum dosyası veya açıklayıcı doküman
• .......

İlişkilendirme farklı mevzuat seti içerisinde yer alan dokümanlar arasında da olabilir. Örneğin Gelir Vergisi Mevzuatı içerisinde yer alan bir doküman veya metin bloğu, Katma Değer Vergisi Mevzuatı içerisinde yer alan bir doküman veya metin bloğu ile ilişkilendirilebilir.

**Comment by arifyildirim** [comment]
[TAMAMLANMADI]

**Comment by hudiys01** [comment]
Kanun Maddelerinin diğer Mevzuat içerikleri ile ilişkilendirilebilmesi sağlandı.
