### ISSUE TITLE
Kanun İçerik Hiyerarşisinde yer alan Node'ların Sıralı hale getirilmesi

### ISSUE THREAD

**Issue by hudiys01** [hudiys01/HUD-IYS#17]

**Comment by hudiys01** [comment]
Var olan verilerede değişikliğin aktarılabilmesi için bir yöntem geliştirildikten sonra deploy yapılacaktır.

**Comment by arifyildirim** [comment]
TREEVİEW İÇERİSİNDE YER ALAN İÇERİĞİN SIRALANMASI İÇİN EKRAN GELİYOR ANCAK YAPILAN DEĞİŞİKLİKLER POPUP EKRAN KAPANDIKTAN SONRA ARKA TARAFA AKTARILMIYOR.

**Comment by hudiys01** [comment]
Kanun Maddelerinin sıralanabilmesi sağlandı.
