### ISSUE TITLE
Madde İçerik Hiyerarşisinde yer alan Node'ların sıralı hale getirilmesi

### ISSUE THREAD

**Issue by hudiys01** [hudiys01/HUD-IYS#18]

**Comment by arifyildirim** [comment]
Madde içerik hiyerarşisinde sonradan ortaya çıkacak ihtiyaçlar çerçevesinde değişiklik yapabilmek için madde düzeyinde bir sequence alanının eklenmesi gerekmektedir. 

örneğin Gelir Vergisi Kanununun 2 inci maddesi yasal değişiklik öncesinde 4 paragraf iken yapılacak yasal bir değişiklik ile 2 inci paragraftan sonra gelmek üzere yeni bir paragraf eklenebilir. toplam paragraf sayısı 5 olurken yeni paragraf üçüncü paragraf olarak eklenir.

bu tür sıralamaları yapmak için ID alanının kullanımı mümkün olmayacağı için madde hiyerarşisi için bir sequence değeri saklamaya ihtiyaç olacaktır.
kanun düzeyindeki sıralama için de (örneğin kurumlar vergisi kanunu içindeki sıralama) (parent node'ın yeterli olmadığı durumlarda) bu tarz bir yapıyı tartışmak gerekebilir.

**Comment by hudiys01** [comment]
Var olan verilerede değişikliğin aktarılabilmesi için bir yöntem geliştirildikten sonra deploy yapılacaktır.

**Comment by arifyildirim** [comment]
[TAMAMLANMADI]

GELEN EKRANDA YERLEŞİM AYARLANIYOR ANCAK ARKA TARAFA YANSIMIYOR...

KONTROL EDİLECEK

**Comment by hudiys01** [comment]
Madde içeriklerinin, bentlerin sıralanabilmesi sağlandı.
