### ISSUE TITLE
Mevzuata ait Tebliğ Oluşturulması

### ISSUE THREAD

**Issue by hudiys01** [hudiys01/HUD-IYS#29]

**Comment by arifyildirim** [comment]
bir kanun tarafından idareye verilen yetki çerçevesinde çıkarılan tebliğler, ait olduğu mevzuat içerisinde tasnif edilen idari dökümanlardır. bu nedenle tebliğlerin ait olduğu mevzuata göre (gelir vergisi mevzuatı, kurumlar vergisi mevzuatı gibi) sınıflandırılması gerekmektedir. zaten tebliğ isimleri de ait olduğu mevzuatı yansıtacak şekilde kullanılmaktadır. örn. 1 Sıra No'lu Kurumlar Vergisi Genel TEbliği gibi.

normal koşullarda bir mevzuat içerisinde ortalama 100 ler le ifade edilen tebliğ metinleri bulunmakta ve bu tebliğ metinlerinin tamamının kanunlarda olduğu gibi yapılandırılması gerekmektedir. özellikle son dönemlerde kanunlardan daha geniş kapsama sahip tebliğlerin çıkarılıyor olması, ilgili dokümanların yapılandırılması gereğini daha da arttırmaktadır.

tebliğler belli bir mevzuat içerisinde yer alsa bile bazen birden fazla kanun ile ilgili olabilir bu nedenle tebliğlerin tamamen veya kısmen birden fazla kanun (mevzuat) ile ilişkilendirilebilir olması gerekir.

uygulama içerisinde tebliğlerin sol panel de yer alan treeview içerisine yerleştirilecek bir link aracılığı ile center panelinde açılacak bir grid de listelenecek ve tebliğ ile ilgili işlemlerin tamamı (tebliğ girişi, yazdırma, vs) bu grid üzerinden yapılacak. söz konusu gridde listelenen ifadelerden hareketle filtreleme, sıralama vb özellikler olmalıdır.

diğer dökümanlarda olduğu gibi tebliğ metinleri içerisinde de tablo, şekil vb unsurlar bulunabileceği için bu aşamadaki veri girişinin mutlaka bir editor aracılığı ile yapılması gerekmektedir. söz konusu editör, tebliğ dışında diğer dokümanların da girişinde kullanılacaktir. sistem içerisine giriş yapılabilecek diğer döküman türlerine (doküman kategorileri) ilişkin örnekler aşağıda yer almaktadır.

• Çifte Vergilendirmeyi Önleme Anlaşmaları
• Vergi Konularında Bilgi Değişim Anlaşmaları
• Gerekçeler
• Kanun Hükmünde Kararnameler
• Bakanlar Kurulu Kararları
• Tüzükler
• Yönetmelikler
• Genel Tebliğler
• Gelir İdaresi Sirkülerleri
• Muktezaları (Özelgeler)
• İç Genelgeler
• Genel Yazılar
• Duyurular
• Rehber/Klavuzlar
• Yargı Kararları
• Sirkülerler
……….
