### ISSUE TITLE
Test ve Production ortamının ayrılması

### ISSUE THREAD

**Issue by arifyildirim** [hudiys01/HUD-IYS#30]
halen geliştirilme aşamasında olan uygulamaya yönelik veri girişlerinin garanti altına alınması amacı ile test ve production ortamının ayrılması ve production tarafında yer alan alacak uygulamanın sadece girilen verilerin görüntülenebilmesi amacı ile internetten erişime açılması gerekmektedir.

**Comment by hudiys01** [comment]
Test ve Production ortamları ayrılmıştır.
Test ortamı için erişim linki :  http://localhost:8080/HUDIYSTEST/pages/login.jsf
Prod ortamı için erişim linki : http://localhost:8080/HUDIYS/pages/login.jsf

Prod ortamda erişim için girilen veriler testdb adındaki veri tabanında saklanacaktır.
Test ortamda oluşturulacak veriler ve tablolar için preproddb adındaki veri tabanı kullanılacaktır.
