### ISSUE TITLE
Madde İçeriğinin Görüntülenmesine Yönelik Formatsal Değişiklikler

### ISSUE THREAD

**Issue by arifyildirim** [hudiys01/HUD-IYS#31]
1) maddeicerik tablosunda yer alan maddeIcerikAdi ve maddeIcerikMetni alanlarının mevcut uzunlukları bazı yerlerde yetersiz kaldığı için veri girişine izin vermiyor. bu nedenle bu iki alanın uzunluğu (maddeIcerikAdi için 150; maddeIcerikMetni için 1250 olabilir) arttırılacak.
2) Uygulama içerisinde madde içeriğinin gösterildiği gride eklenmiş altnode ların sürekli açık gelmesi sağlanacak. 
3) 2 inci bentte bahsedilen gridin yazı fontu arttırılacak ve herhangi bir çerçeve veya kenarlık görüntülenmeyecek.

**Comment by hudiys01** [comment]
1-MaddeIcerikAdı 150, MaddeIcerikMetin 1250 karakter olarak değiştirilmiştir.
2-Altnodelar açık hale getirilmiştir.
3-Font büyütülmüştür.
4-Treetable'a ait çerçeveler kaldırılmıştır.
