### ISSUE TITLE
Production'a yapılacak deploy ...

### ISSUE THREAD

**Issue by arifyildirim** [hudiys01/HUD-IYS#42]
arayüzlerin internete açık olması nedeni ile oluşabilecek hataların engellenmesi için, halen HUD IYS test uygulamasında olan kısmın production tarafına aktarılması sırasında, aşağıda yer alan bileşenlerin, geçici bir süre ekrandan kaldırılması (ilgili kod kısmı not haline getirilerek yapılabilir.) gerekiyor.

1) Login ekranında yer alan üst menü (kullanıcı herhangi bir şifre girmeden ilgili butona basında ilgili sayfaya gidebiliyor)

![1](https://cloud.githubusercontent.com/assets/7935860/3633647/3786cc8e-0eed-11e4-9a22-5991c0ff2b2b.png)

2)Kanunların görüntülendiği kanunIcerik sayfasında yer alan toolbar ve buton (internet üzerinde uygulamaya bakan kişilerin yanlışlıkla içerik ekleme ve silmelerini engellemek için)

![2](https://cloud.githubusercontent.com/assets/7935860/3633649/58a5e5ee-0eed-11e4-9b0a-aad9b2936145.png)

3) Tebliğlerin görüntülendiği tebligIcerik sayfasında yer alan toolbar ve buton (internet üzerinde uygulamaya bakan kişilerin yanlışlıkla içerik ekleme ve silmelerini engellemek için)
![3](https://cloud.githubusercontent.com/assets/7935860/3633651/838fd3f0-0eed-11e4-9525-53858f1e7541.png)

**Comment by hudiys01** [comment]
Productiona yapılan deploylarda yukarıda belirtilenlere dikkat edilmektedir.
