### ISSUE TITLE
Logo Görüntülenmiyor

### ISSUE THREAD

**Issue by arifyildirim** [hudiys01/HUD-IYS#43]
sayfaların üst köşesinde yer alan logo, ilgili sayfalara internet üzerinden erişildiğinde görüntülenmiyor.

![4](https://cloud.githubusercontent.com/assets/7935860/3633658/20bec80c-0eee-11e4-815f-6358181398eb.png)

**Comment by hudiys01** [comment]
Logonun görüntülenmesi sağlandı.
