### ISSUE TITLE
içerik no ve içerik adı tanımlaması

### ISSUE THREAD

**Issue by arifyildirim** [hudiys01/HUD-IYS#44]
aşağıda da görüleceği üzere uygulama içerisine eklenen yeni içeriklerde içerik no ile içerik adı arasında otomatik olarak ":" (iki nokta üstüste) karakteri ekleniyor.
![1](https://cloud.githubusercontent.com/assets/7935860/3635669/58d9dcbe-0f83-11e4-8a56-1a4c7f1f96ba.png)

ancak başta tebliğ olmak üzere diğer metinlerinde yer alan başlıklarda içerik no ile içerik adı arasında "-" "." gibi farklı karakterlerin koyulması söz konusu olacak. bu nedenle içerik no ile içerik adı arasında yerleştirilecek karakterin veri girişi sırasında seçtirilmesi gerekiyor.

**Comment by arifyildirim** [comment]
[TAMAMLANMADI]

ÖRNEĞİN İLK ÇIKAN TEBLİĞLERDE İÇERİK NO İLE İÇERİK ADI ARASINDA : YERİNE _ KARAKTERİ KOYULMALI.

BU NEDENLE İLGİLİ ALANIN SERBEST ŞEKİLDE BELİRLENMESİ SAĞLANACAK

**Comment by hudiys01** [comment]
Karakterin veri girişi sırasında belirlenmesi sağlandı.
