### ISSUE TITLE
Okuma Modu

### ISSUE THREAD

**Issue by arifyildirim** [hudiys01/HUD-IYS#45]
Uygulama içerisinde yer alan dökümanların treeview aracılığı ile okunmasına ilave olarak "Okuma Modu" altında tüm dökümanın (Tüm kanun, tüm tebliğ ve eklenecek diğer döküman türleri) aynı anda görüntülenmesi ve okunması sağlanacak.

**Comment by hudiys01** [comment]
Okuma modu ile kastedilen tüm kanun metninin orta içerik alanında ekranda dökülmesi midir yoksa çıktı alınmak üzere yayınlanması mıdır?

**Comment by arifyildirim** [comment]
şu an itibari ile acil ihtiyacımız, kısım kısım girdiğimiz ve sol taraftaki
treeview aracılığı ile gezindiğimiz dökümanların (kanun tebliğ veya
diğerleri) girişlerinde herhangi bir hata olup olmadığını kontrol etmek
amacı ile bütün halinde ve hiyerarşik yapısına uygun bir şekilde ekranda
görüntülenmesi.

ilgili dökümanların basılı hale getirilip kullanıcılara elektronik veya
kağıt ortamında sunulmasını projenin sonlarına doğru konuşuyor oluruz.

2014-07-23 9:39 GMT+03:00 hudiys01 notifications@github.com:

> Okuma modu ile kastedilen tüm kanun metninin orta içerik alanında ekranda
> dökülmesi midir yoksa çıktı alınmak üzere yayınlanması mıdır?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hudiys01/HUD-IYS/issues/45#issuecomment-49838228.

## 

Arif YILDIRIM

**Comment by arifyildirim** [comment]
Okuma modu ile ilgili olarak tanımlanan ihtiyacı biraz daha değiştirip açılan herhangi bir dokümanın (Kanun, tebliğ yönetmelik vb...) center bolmesindeki gride bütün halinde yüklenmesini ihtiyaç duyulan navigasyon için de sol da yer alan treeview veya center bölmesinin scroll bar ile kaydırılması gibi seçenekler ile sağlanması daha faydalı olacak... 
benzer yaklaşım word gibi editorlerde (navigasyon paneli) mevcut.

![1](https://cloud.githubusercontent.com/assets/7935860/3818980/12f5aa6e-1ce6-11e4-8423-03874f48b86d.png)

**Comment by arifyildirim** [comment]
Gelir İdaresi Başkanlığı sitesinde yer alan mevzuat uygulamasında seçili kanun metninin tamamının görüntülenmesi için "Tüm Kanunu Göster" seçeneği var. burada bu tarz bir yaklaşım da benimsenebilir.

Aşağıdaki ekranda öncelikle Gelir Vergisi Kanunu sonrasında ise "Tüm Kanunu Görüntüle" seçeneği seçiliyor.
![1](https://cloud.githubusercontent.com/assets/7935860/4111849/a95c9ad8-3214-11e4-94a6-b7c11262f096.png)

![2](https://cloud.githubusercontent.com/assets/7935860/4111850/adff90cc-3214-11e4-984d-6a58229c5a3c.png)

yukarıda kanun için öngördüğümüz olayı sistem içerisindeki tüm dökümanlar için de kurgulamamız gerekiyor.

**Comment by arifyildirim** [comment]
[TAMAMLANMADI]

OKUMA MODU FORMATININ İLGİLİ METNİN BASIMA HAZIR OLACAKMIŞ GİBİ GÖRÜNTÜLENMESİ GEREKİYOR. KANUN METİNLERİ İÇİN MADDE İÇERİKLERİ SOLA YASLI DİĞERLERİNİN İSE ORTALI VE BOLD KARAKTERLER İLE YAZILMASI SAĞLANACAK. 

ÖRNEK GÖRÜNTÜ YUKARIDA MEVCUT.

**Comment by hudiys01** [comment]
Kanun içeriğinin istenilen formatta gösterilmesi sağlandı.
