### ISSUE TITLE
Kanun dışındaki metinlerde başlık görünümü

### ISSUE THREAD

**Issue by arifyildirim** [hudiys01/HUD-IYS#46]
Kanun metinlerinin aksine uygulama içerisinde yer alan diğer metinlere ait başlık görünümleri, treeview da olduğu gibi ve tek satırda görüntülecek. örneğin aşağıda yer alan ekran görüntüsündeki başlık görüntüsü 
"1. Verginin Konusunu Teşkil Eden İşlemler" şeklinde olmalı. (İçerik No ile İçerik Adı arasında farklı karakterler eklenmesi ile ilgili daha önce yeni bir istek açılmıştı.)
![1](https://cloud.githubusercontent.com/assets/7935860/3635687/c1901236-0f84-11e4-93e7-dee84a9e5988.png)

**Comment by hudiys01** [comment]
Gerekli değişiklik yapıldı.
