### ISSUE TITLE
Büyük Tabloların Veri Girişi sırasında yaşananan problemin giderilmesi

### ISSUE THREAD

**Issue by arifyildirim** [hudiys01/HUD-IYS#47]
aşağıda ekran görüntüsü yer alan ve http://www.gib.gov.tr/index.php?id=1028 adresinde yer alan tabloyu tebliğ içerisine tek bir içerik olarak yerleştirmem gerekiyor. ancak veri boyutu nedeni ile program hata üretiyor. bu tarz tablolar kanun metinlerin de de söz konusu olacak.

![1](https://cloud.githubusercontent.com/assets/7935860/3665531/d8c34cac-11e6-11e4-9335-12d80b55934e.png)

Tebliğ ekinde yer alabilecek başka büyük bir tablo örneği için  3 SERİ NO'LU GELİR VERGİSİ GENEL TEBLİĞİ ne bakılabilir.

**Comment by hudiys01** [comment]
Veri alanının boyutu artırılarak sorun giderilmiştir.

**Comment by arifyildirim** [comment]
http://www.gib.gov.tr/fileadmin/mevzuatek/otv_oranlari_tum/ozeltuketimoranlari-OpenPage.htm

(OTV 

adresinde yer alan tarife bilgileri gibi büyük tabloların girişi hala problem oluyor. 

bu tür boyutu öngörülemeyen içerikleri PDF şeklinde upload etme imkanı verilebilir mi?

girişi yapılamayan bir tablo örneği için

http://www.gib.gov.tr/fileadmin/mevzuatek/otv_oranlari_tum/15_06_2012_IV_Sayili_Liste.htm
