### ISSUE TITLE
Treeview

### ISSUE THREAD

**Issue by arifyildirim** [hudiys01/HUD-IYS#48]
Gerek Kanun gerekse tebliğ metinin hiyerarşisini göstermek amacı ile kullandığımız treview, her bir node ekleme işleminde kendisini kapatıyor. bu ise içerik girişinden önce eklenen nodun açılması gereğini ortaya çıkarıyor. 
![1](https://cloud.githubusercontent.com/assets/7935860/3666270/114be324-11ef-11e4-9d9c-33359a09e465.png)

Bu nedenle treeview bileşeninin;

1) Node ekleme işleminden sonra eklenen en son node seçili olacak şekilde açık hale gelmesi ve 
2) kullanım kolaylığı açısından içinde bulunduğu panelin tamamını kapsayacak hale getirilmesi

sağlanacak.

**Comment by hudiys01** [comment]
Gerekli değişiklikler yapılmıştır.
