### ISSUE TITLE
Dokümanların Durum Bilgisi

### ISSUE THREAD

**Issue by arifyildirim** [hudiys01/HUD-IYS#49]
Uygulama içine girilecek her bir yasal dökumanın (kanun, tebliğ vb...) durumunu (güncel, güncelliği kalmamıştır, kaldırılmıştır. .... gibi) belirtmek amacı ile kullanılabilecek bir alan eklenecek. ilgili dökümanların durumu metin veya görüntü ile ifade edilecek.
![1](https://cloud.githubusercontent.com/assets/7935860/3666372/8f39c480-11f0-11e4-810f-e5e1bb200b36.png)

**Comment by hudiys01** [comment]
1-Daha önce girilmiş olan bir içeriğin silinmesi mümkün olacak mı?(Yanlışlıkla doğru girilmemiş olabilir, ekrandan silinebilmesi isteniyor mu yoksa veri tabanından elle silinmesi mi düşünülüyor.)
2-Bir içerik arşivlendikten sonra hangi duruma düşmüş olacak "kaldırılmıştır" durumuna mı düşecek yoksa durum değişikliği yapılması arşivleme işleminden tamamen bağımsız mı? 
3-Bir içerik arşivlendikten sonra hiç görüntülenmemesi mi düşünülüyor yoksa "arşivlenmiştir" durum bilgisiyle ekranda görüntülenmesi mi düşünülüyor?

**Comment by arifyildirim** [comment]
Yapılan girişlerin silinmesi söz konusu olacaktır ama bu yetkiyi veri
girişi yapacak tüm kişilere vermemiz söz konusu değil. (Muhtemelen bizim
tarafta bir yönetici yetkilendirilir) bunun için silme ile ilgili işlemleri
kodun durumuna göre bir süre veritabanından yürütüp ilgili arayüzleri
sonraki aşamada geliştirebiliriz.

İstek metni içerisinde ifade edilen durum bilgisi söz konusu dokümanın
mevzuat karşısındaki durumlarını anlatmak içindi. yani bir tebliğ
yayınlanmıştır. dayanak teşkil eden maddesi kaldırıldığı veya süresi
geçtiği için güncelliği kalmamıştır. ya da kanun eski bir kanundur
güncelliği yoktur ama yine de kullanıcıların bakmaya ihtiyaçları olabilir.
(Zamanaşımı nedeni ile) bu nedenle durum bilgisinin hukuki durumu şeklinde
değerlendirmek daha doğru. şu an itibari ile girilen tüm içeriklerin
görüntüleneceği düşünüldüğünden arşiv kurgusunu projenin sonraki
safhalarına bırakılabiliriz.

2014-07-23 12:02 GMT+03:00 hudiys01 notifications@github.com:

> 1-Daha önce girilmiş olan bir içeriğin silinmesi mümkün olacak
> mı?(Yanlışlıkla doğru girilmemiş olabilir, ekrandan silinebilmesi isteniyor
> mu yoksa veri tabanından elle silinmesi mi düşünülüyor.)
> 2-Bir içerik arşivlendikten sonra hangi duruma düşmüş olacak
> "kaldırılmıştır" durumuna mı düşecek yoksa durum değişikliği yapılması
> arşivleme işleminden tamamen bağımsız mı?
> 3-Bir içerik arşivlendikten sonra hiç görüntülenmemesi mi düşünülüyor
> yoksa "arşivlenmiştir" durum bilgisiyle ekranda görüntülenmesi mi
> düşünülüyor?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hudiys01/HUD-IYS/issues/49#issuecomment-49849203.

## 

Arif YILDIRIM

**Comment by hudiys01** [comment]
Kanun ve Tebliğlere ait durum bilgisi ilgili tablo alanına eklendi.
Sisteme Güncel, Güncel Değil ve Kaldırıldı adlı üç durum ve bu durumlara ait ikonlar eklendi.

![image](https://cloud.githubusercontent.com/assets/7929765/4052328/4dfe563a-2d6a-11e4-8925-38909c03fb83.png)
