### ISSUE TITLE
Uygulama performansı ile ilgili sorunlar

### ISSUE THREAD

**Issue by arifyildirim** [hudiys01/HUD-IYS#50]
1) özellikle en son deploydan sonra gerek test gerekse production uygulaması bir süre işlev gördükten sonra yeni isteklere yanıt vermemeye başlıyor.
uygulama sunucusunu kapatıp açtığımda ise normale dönüyor. ancak bu işlem çok sık olmaya başladı.

2) kanun metinleri içinde gezinirken kullandığımız treeview özellikle büyük kanunlarda özellikle çok yavaş çalışıyor.

**Comment by hudiys01** [comment]
Uygulama sunucusuna ait bellek artırılarak performans sorunu giderildi.
