### ISSUE TITLE
Daha önce girilen metin içeriklerin düzenlenebilmesi

### ISSUE THREAD

**Issue by arifyildirim** [hudiys01/HUD-IYS#51]
uygulamanın mevcut halinde, daha önce girilen herhangi bir kanun maddesi veya tebliğ metnine ait içeriğin yeniden düzenlenmesi mümkün değil.
söz konusu içeriklerin editor ile yeniden düzenlenmesi sağlanacak.
(bu husus özellikle bizim veritabanına doğrudan giriş yaptığımız kanun metinlerinin biçimlendirilmesi açısından önemli)

**Comment by hudiys01** [comment]
Kanun ve Tebliğler ait maddelerin ve madde içeriklerinin ekranlar vasıtasıyla düzenlenebilmesi sağlandı.
