### ISSUE TITLE
Veri girişi sırasında kullanılan bazı tuş bileşenleri sonrası "İlgili İçerikler" paneli açılıp kapanıyor.

### ISSUE THREAD

**Issue by arifyildirim** [hudiys01/HUD-IYS#52]
Yeni Kanun Maddesi girişi için ilgili form (muhtemelen diğer formlarda da aynı sorun söz konusu) açılıp form üzerindeki bileşenlerde metin seçmek için kullanılan bazı tuş bileşenleri kullanıldığında "İlgili İçerikler" paneli açılıp kapanıyor.

metin girişi için ilgili form açıldığındaki görünüm.

![1](https://cloud.githubusercontent.com/assets/7935860/4024404/939a1d72-2bc7-11e4-86fc-24ce1eb62a85.png)

ctrl + alt + sağ ok tuş bileşenine basılıktan sonraki görünüm.

![2](https://cloud.githubusercontent.com/assets/7935860/4024412/f1bebe12-2bc7-11e4-84aa-667fd27e2060.png)

**Comment by hudiys01** [comment]
Sorun giderilmiştir.
