### ISSUE TITLE
İçeriği çok fazla olan bentlerin eklenmesi için bir yöntem geliştirilecek

### ISSUE THREAD

**Issue by hudiys01** [hudiys01/HUD-IYS#55]
Eklenecek metin veya tablonun attachment olarak eklenmesi sağlanabilir.

**Comment by arifyildirim** [comment]
online mevzuat sistemi olarak tasarladığımız ancak aslında bir içerik yönetim sistemi olan yapı içerisine farklı içeriklerin eklenmesi söz konusu olacağı için söz konusu gereksinimini farklı dosya eklenmesi şeklinde kurgulamak daha anlamlı olacaktır.

Şu an itibari ile metin veya tablonun attachment olarak eklenmesi şeklinde tanımlandığımız çerçevede aşağıdaki ilave durumlar söz konusu olabilir. 

.... TEbliği içerisinde yer alan resim dosyası.

... Tebliği ekinde yer alan dilekçe örnekleri 
..... yönetmeliği ekinde yer alan yazı veya teknik çizim örnekleri.

Gelir Vergisi Kanununun 94'üncü maddesi uygulaması ile ilgili olarak yapılmış bir sunum (ppt, pdf video) dosyası

Kurumlar Vergisi Kanunu İstisnalar ile ilgili hazırlanmış bir video dosyası ....

bunun için söz konusu yapı farklı içeriklerin eklenmesi şeklinde kurgulanacak...

**Comment by arifyildirim** [comment]
[TAMAMLANMADI]
