### ISSUE TITLE
İlgili İçerikler Paneli

### ISSUE THREAD

**Issue by arifyildirim** [hudiys01/HUD-IYS#59]
İlgili içerikler paneli, mevzuat setinde ilişki tanımı olan içerik türlerine göre otomatik olarak doldurulacak.

örneğin gelir vergisi kanununda sadece ilgili kanun maddeleri ve ilgili tebliğler tanımı var. bu durumda aşağıda yer alan panel görüntüsünün sadece ilgili kanun maddeleri ve ilgili tebliğleri içerecek şekilde doldurulması, diğer başlıkların ise (genelge, tüzük vs) panelde yer almaması gerekiyor.  bu durum mevzuat seti içerisinde yer alan türlere göre dinamik olacaktır.
![untitled](https://cloud.githubusercontent.com/assets/7935860/4517522/bc3db47c-4c3e-11e4-9957-ea87e2642243.png)

**Comment by hudiys01** [comment]
İlgili İçerik Paneli dinamik hale getirilmiştir.
