### ISSUE TITLE
Seçenekler menüsü

### ISSUE THREAD

**Issue by arifyildirim** [hudiys01/HUD-IYS#61]
içerik panelinde yer alan seçenekler menüsü, sol panelde yer alan treeview üzerinde olduğu gibi toolbar şeklinde değiştirilecek. sol tarafta yer alan tüm kanunu göster butonu da içerik paneli üzerinde oluşturulacak toolbara eklenecek 

![untitled](https://cloud.githubusercontent.com/assets/7935860/4517549/ed6cf280-4c41-11e4-8f6d-93d1f2d5b718.png)

**Comment by hudiys01** [comment]
Toolbar haline getirildi.
