### ISSUE TITLE
Kanun maddesi Tebliğ ilişkilendirme

### ISSUE THREAD

**Issue by arifyildirim** [hudiys01/HUD-IYS#63]
herhangi bir kanun maddesi veya maddesi içerisinde yer alan içerikten (fıkra, bent vs) tebliğe ilişki kurulacağı zaman ilgili tebliğin tamamına da ilişki kurulabilmeli.
örneğin aşağıda yer alan ekranda bir maddeden tebliğin sadece bir bölümüne (I Genel Bilgi) ilişki kurulabiliyor. söz konusu tebliğin tamamı ilgili madde ile ilişkili olabilir.

![untitled](https://cloud.githubusercontent.com/assets/7935860/4517668/cd9ac3e6-4c4c-11e4-8c71-6ca30145487f.png)

**Comment by hudiys01** [comment]
Tebliğin ya da kanunun tamamına ilişki kurulabilmesi sağlandı.
